# site settings
title: Francisco Valladolid Blog
subtitle: BSD & Linux Weblog
email: ficovh@gmail.com
description: Linux and BSD, Python and Perl blog.
baseurl: "/"
url: "https://blog.bsdguy.org"
author: ficovh

# social settings
facebook_url: https://facebook.com/vmicrosistemas
dribble_url: https://dribbble.com/
tumblr_url: https://tumblr.com/
instagram_url: https://instagram.com/ficovh
twitter_url: https://twitter.com/ficovh
github_url: https://github.com/ficovh
stackoverflow_url: https://stackoverflow.com/
linkedin_url: https://linkedin.com/

formspree_url: https://formspree.io/xqkyrway

collections:
  projects:
    output: true

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num/"
